/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package salmans;

import Clases.*;
import java.util.AbstractQueue;
import java.util.ArrayList;
import java.util.Queue;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;

/**
 *
 * @author Walther
 */
public class gui extends javax.swing.JFrame {

    /**
     * Creates new form gui
     */
    public gui() {
        initComponents();
        Camion camion = new Camion();
        camiones.add(camion);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        guiOrdenar = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaMenu_guiMenu = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jlTotal_guiMenu = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        guiCocina = new javax.swing.JDialog();
        lbCocinero4 = new javax.swing.JLabel();
        lbCocinero3 = new javax.swing.JLabel();
        lbCocinero2 = new javax.swing.JLabel();
        barra1 = new javax.swing.JProgressBar();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lbCocinero1 = new javax.swing.JLabel();
        barra3 = new javax.swing.JProgressBar();
        barra2 = new javax.swing.JProgressBar();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        lbCocinero5 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        barra15 = new javax.swing.JProgressBar();
        barra18 = new javax.swing.JProgressBar();
        barra19 = new javax.swing.JProgressBar();
        barra20 = new javax.swing.JProgressBar();
        barra17 = new javax.swing.JProgressBar();
        barra16 = new javax.swing.JProgressBar();
        barra7 = new javax.swing.JProgressBar();
        barra10 = new javax.swing.JProgressBar();
        barra11 = new javax.swing.JProgressBar();
        barra13 = new javax.swing.JProgressBar();
        barra14 = new javax.swing.JProgressBar();
        jLabel77 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        barra6 = new javax.swing.JProgressBar();
        jLabel74 = new javax.swing.JLabel();
        barra4 = new javax.swing.JProgressBar();
        jLabel73 = new javax.swing.JLabel();
        barra5 = new javax.swing.JProgressBar();
        jLabel72 = new javax.swing.JLabel();
        barra9 = new javax.swing.JProgressBar();
        barra8 = new javax.swing.JProgressBar();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        barra12 = new javax.swing.JProgressBar();
        guiBodega = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaProductos_guiBodega = new javax.swing.JList();
        jLabel4 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        guiEnviar = new javax.swing.JDialog();
        guiCrearProducto = new javax.swing.JDialog();
        cbIngredientes_guiCrearProducto = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        tfNombreProducto_guiCrearProducto = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tfTiempoProducto = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        tfPrecioProducto = new javax.swing.JTextField();
        jButton11 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        listaIngredientes_guiCrearProducto = new javax.swing.JList();
        guiComprarIngredientes = new javax.swing.JDialog();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tfNombreIngrediente = new javax.swing.JTextField();
        jButton12 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        jScrollPane1.setViewportView(listaMenu_guiMenu);

        jLabel2.setText("Menu");

        jLabel3.setText("Total: L.");

        jlTotal_guiMenu.setText("0.0");

        jButton5.setText("Agregar");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        jButton6.setText("Terminar Orden");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout guiOrdenarLayout = new javax.swing.GroupLayout(guiOrdenar.getContentPane());
        guiOrdenar.getContentPane().setLayout(guiOrdenarLayout);
        guiOrdenarLayout.setHorizontalGroup(
            guiOrdenarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, guiOrdenarLayout.createSequentialGroup()
                .addGroup(guiOrdenarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(guiOrdenarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(guiOrdenarLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(guiOrdenarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(guiOrdenarLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlTotal_guiMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(60, 60, 60))
        );
        guiOrdenarLayout.setVerticalGroup(
            guiOrdenarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(guiOrdenarLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel2)
                .addGroup(guiOrdenarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(guiOrdenarLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, guiOrdenarLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addComponent(jButton5)
                        .addGap(18, 18, 18)
                        .addComponent(jButton6)
                        .addGap(68, 68, 68)
                        .addGroup(guiOrdenarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jlTotal_guiMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53))))
        );

        lbCocinero4.setText("Inactivo");

        lbCocinero3.setText("Inactivo");

        lbCocinero2.setText("Inactivo");

        jLabel13.setText("Nombre del Cocinero");

        jLabel14.setText("Tiempo");

        lbCocinero1.setText("Inactivo");

        jLabel64.setText("Inactivo");

        jLabel65.setText("Inactivo");

        lbCocinero5.setText("Inactivo");

        jLabel63.setText("Inactivo");

        jLabel68.setText("Inactivo");

        jLabel69.setText("Inactivo");

        jLabel66.setText("Inactivo");

        jLabel67.setText("Inactivo");

        jLabel77.setText("Inactivo");

        jLabel76.setText("Inactivo");

        jLabel75.setText("Inactivo");

        jLabel74.setText("Inactivo");

        jLabel73.setText("Inactivo");

        jLabel72.setText("Inactivo");

        jLabel70.setText("Inactivo");

        jLabel71.setText("Inactivo");

        javax.swing.GroupLayout guiCocinaLayout = new javax.swing.GroupLayout(guiCocina.getContentPane());
        guiCocina.getContentPane().setLayout(guiCocinaLayout);
        guiCocinaLayout.setHorizontalGroup(
            guiCocinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 314, Short.MAX_VALUE)
            .addGroup(guiCocinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(guiCocinaLayout.createSequentialGroup()
                    .addGap(13, 13, 13)
                    .addGroup(guiCocinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(guiCocinaLayout.createSequentialGroup()
                            .addComponent(jLabel13)
                            .addGap(52, 52, 52)
                            .addComponent(jLabel14))
                        .addGroup(guiCocinaLayout.createSequentialGroup()
                            .addComponent(lbCocinero1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(barra1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(guiCocinaLayout.createSequentialGroup()
                            .addComponent(lbCocinero2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(barra2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(guiCocinaLayout.createSequentialGroup()
                            .addGroup(guiCocinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbCocinero3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbCocinero4, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbCocinero5, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel64, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel65, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel63, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel67, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel72, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel73, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel70, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel69, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel68, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel66, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel71, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel74, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel75, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel77, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel76, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(guiCocinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(barra3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(barra4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(barra5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(barra6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(barra7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(barra8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(barra9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(barra10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(barra11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(barra12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(barra13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(barra14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(barra15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(barra16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(barra17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(barra18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(barra19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(barra20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addContainerGap(40, Short.MAX_VALUE)))
        );
        guiCocinaLayout.setVerticalGroup(
            guiCocinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 790, Short.MAX_VALUE)
            .addGroup(guiCocinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(guiCocinaLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(guiCocinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(guiCocinaLayout.createSequentialGroup()
                            .addGroup(guiCocinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(guiCocinaLayout.createSequentialGroup()
                                    .addGroup(guiCocinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(guiCocinaLayout.createSequentialGroup()
                                            .addGroup(guiCocinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(guiCocinaLayout.createSequentialGroup()
                                                    .addGroup(guiCocinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel13)
                                                        .addComponent(jLabel14))
                                                    .addGap(18, 18, 18)
                                                    .addGroup(guiCocinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(barra1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(lbCocinero1))
                                                    .addGap(24, 24, 24)
                                                    .addComponent(barra2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(lbCocinero2))
                                            .addGap(24, 24, 24)
                                            .addComponent(barra3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(24, 24, 24)
                                            .addComponent(barra4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, guiCocinaLayout.createSequentialGroup()
                                            .addComponent(lbCocinero3)
                                            .addGap(38, 38, 38))
                                        .addComponent(lbCocinero4, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addGap(24, 24, 24)
                                    .addComponent(barra5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(24, 24, 24)
                                    .addComponent(barra6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(24, 24, 24)
                                    .addComponent(barra7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(24, 24, 24)
                                    .addComponent(barra8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(guiCocinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(guiCocinaLayout.createSequentialGroup()
                                        .addGroup(guiCocinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(guiCocinaLayout.createSequentialGroup()
                                                .addComponent(lbCocinero5)
                                                .addGap(38, 38, 38))
                                            .addComponent(jLabel64))
                                        .addGap(76, 76, 76))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, guiCocinaLayout.createSequentialGroup()
                                        .addComponent(jLabel65)
                                        .addGap(38, 38, 38))
                                    .addComponent(jLabel63, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGap(24, 24, 24)
                            .addComponent(barra9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(24, 24, 24)
                            .addComponent(barra10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(24, 24, 24)
                            .addComponent(barra11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(24, 24, 24)
                            .addComponent(barra12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(24, 24, 24)
                            .addComponent(barra13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(24, 24, 24)
                            .addComponent(barra14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(24, 24, 24)
                            .addComponent(barra15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(24, 24, 24)
                            .addComponent(barra16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(guiCocinaLayout.createSequentialGroup()
                            .addGroup(guiCocinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(guiCocinaLayout.createSequentialGroup()
                                    .addGroup(guiCocinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(guiCocinaLayout.createSequentialGroup()
                                            .addComponent(jLabel67)
                                            .addGap(38, 38, 38))
                                        .addComponent(jLabel72))
                                    .addGap(76, 76, 76))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, guiCocinaLayout.createSequentialGroup()
                                    .addComponent(jLabel73)
                                    .addGap(38, 38, 38))
                                .addComponent(jLabel70, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGap(152, 152, 152))
                        .addGroup(guiCocinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(guiCocinaLayout.createSequentialGroup()
                                .addGroup(guiCocinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(guiCocinaLayout.createSequentialGroup()
                                        .addComponent(jLabel69)
                                        .addGap(38, 38, 38))
                                    .addComponent(jLabel68))
                                .addGap(76, 76, 76))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, guiCocinaLayout.createSequentialGroup()
                                .addComponent(jLabel66)
                                .addGap(38, 38, 38))
                            .addComponent(jLabel71, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGap(24, 24, 24)
                    .addGroup(guiCocinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(guiCocinaLayout.createSequentialGroup()
                            .addComponent(barra17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(24, 24, 24)
                            .addComponent(barra18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(24, 24, 24)
                            .addComponent(barra19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(24, 24, 24)
                            .addComponent(barra20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(guiCocinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(guiCocinaLayout.createSequentialGroup()
                                .addGroup(guiCocinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(guiCocinaLayout.createSequentialGroup()
                                        .addComponent(jLabel74)
                                        .addGap(38, 38, 38))
                                    .addComponent(jLabel75))
                                .addGap(76, 76, 76))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, guiCocinaLayout.createSequentialGroup()
                                .addComponent(jLabel77)
                                .addGap(38, 38, 38))
                            .addComponent(jLabel76, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jScrollPane2.setViewportView(listaProductos_guiBodega);

        jLabel4.setText("Bodega");

        jButton7.setText("Crear Producto");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });

        jButton8.setText("Listar Ingredientes");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });

        jButton9.setText("Comprar Ingredientes");
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout guiBodegaLayout = new javax.swing.GroupLayout(guiBodega.getContentPane());
        guiBodega.getContentPane().setLayout(guiBodegaLayout);
        guiBodegaLayout.setHorizontalGroup(
            guiBodegaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(guiBodegaLayout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(guiBodegaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(guiBodegaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );
        guiBodegaLayout.setVerticalGroup(
            guiBodegaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(guiBodegaLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel4)
                .addGap(46, 46, 46)
                .addGroup(guiBodegaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(guiBodegaLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jButton7)
                        .addGap(18, 18, 18)
                        .addComponent(jButton8)
                        .addGap(18, 18, 18)
                        .addComponent(jButton9)))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout guiEnviarLayout = new javax.swing.GroupLayout(guiEnviar.getContentPane());
        guiEnviar.getContentPane().setLayout(guiEnviarLayout);
        guiEnviarLayout.setHorizontalGroup(
            guiEnviarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        guiEnviarLayout.setVerticalGroup(
            guiEnviarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jLabel5.setText("Crear Producto");

        jLabel6.setText("Ingredientes");

        jLabel7.setText("Nombre");

        jLabel8.setText("Tiempo de Cocina");

        jButton10.setText("ADD");
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton10MouseClicked(evt);
            }
        });

        jLabel9.setText("Precio:");

        jButton11.setText("Listo");
        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton11MouseClicked(evt);
            }
        });

        jScrollPane3.setViewportView(listaIngredientes_guiCrearProducto);

        javax.swing.GroupLayout guiCrearProductoLayout = new javax.swing.GroupLayout(guiCrearProducto.getContentPane());
        guiCrearProducto.getContentPane().setLayout(guiCrearProductoLayout);
        guiCrearProductoLayout.setHorizontalGroup(
            guiCrearProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(guiCrearProductoLayout.createSequentialGroup()
                .addGroup(guiCrearProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(guiCrearProductoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(guiCrearProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(67, 67, 67)
                        .addGroup(guiCrearProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbIngredientes_guiCrearProducto, 0, 123, Short.MAX_VALUE)
                            .addComponent(tfNombreProducto_guiCrearProducto)
                            .addComponent(tfTiempoProducto)
                            .addComponent(tfPrecioProducto))
                        .addGap(18, 18, 18)
                        .addComponent(jButton10)
                        .addGap(123, 123, 123)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE))
                    .addGroup(guiCrearProductoLayout.createSequentialGroup()
                        .addGroup(guiCrearProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(guiCrearProductoLayout.createSequentialGroup()
                                .addGap(302, 302, 302)
                                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(guiCrearProductoLayout.createSequentialGroup()
                                .addGap(293, 293, 293)
                                .addComponent(jLabel5)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        guiCrearProductoLayout.setVerticalGroup(
            guiCrearProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(guiCrearProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(57, 57, 57)
                .addGroup(guiCrearProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(guiCrearProductoLayout.createSequentialGroup()
                        .addGroup(guiCrearProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbIngredientes_guiCrearProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jButton10))
                        .addGap(46, 46, 46)
                        .addGroup(guiCrearProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfNombreProducto_guiCrearProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(39, 39, 39)
                        .addGroup(guiCrearProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(tfTiempoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(59, 59, 59)
                        .addGroup(guiCrearProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(tfPrecioProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jButton11)
                .addGap(19, 19, 19))
        );

        jLabel10.setText("Mercadito");

        jLabel11.setText("Nombre: ");

        jButton12.setText("Agregar");
        jButton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton12MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout guiComprarIngredientesLayout = new javax.swing.GroupLayout(guiComprarIngredientes.getContentPane());
        guiComprarIngredientes.getContentPane().setLayout(guiComprarIngredientesLayout);
        guiComprarIngredientesLayout.setHorizontalGroup(
            guiComprarIngredientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(guiComprarIngredientesLayout.createSequentialGroup()
                .addGroup(guiComprarIngredientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(guiComprarIngredientesLayout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jLabel10))
                    .addGroup(guiComprarIngredientesLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel11)
                        .addGap(104, 104, 104)
                        .addComponent(tfNombreIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(guiComprarIngredientesLayout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jButton12)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        guiComprarIngredientesLayout.setVerticalGroup(
            guiComprarIngredientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(guiComprarIngredientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(36, 36, 36)
                .addGroup(guiComprarIngredientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tfNombreIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(jButton12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salmans/salmans.jpg"))); // NOI18N

        jButton1.setText("Ordenar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setText("Bodega");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jButton3.setText("Cocina");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jButton4.setText("Enviar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(268, 268, 268)
                .addComponent(jLabel1)
                .addContainerGap(258, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(354, 354, 354))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(78, 78, 78)
                .addComponent(jButton1)
                .addGap(60, 60, 60)
                .addComponent(jButton2)
                .addGap(69, 69, 69)
                .addComponent(jButton3)
                .addGap(74, 74, 74)
                .addComponent(jButton4)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton12MouseClicked
        String nombreIngrediente = tfNombreIngrediente.getText();
        b.addIngrediente(nombreIngrediente);
        tfNombreIngrediente.setText("");
        JOptionPane.showMessageDialog(null, "Ingrediente Agregado");
    }//GEN-LAST:event_jButton12MouseClicked

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        ComboBoxModel modelo = cbIngredientes_guiCrearProducto.getModel();
        cbIngredientes_guiCrearProducto.removeAllItems();
        for (int i = 0; i < b.size(); i++) {
            cbIngredientes_guiCrearProducto.addItem(b.get(i));
        }
        guiCrearProducto.setModal(true);
        guiCrearProducto.pack();
        guiCrearProducto.setVisible(true);
    }//GEN-LAST:event_jButton7MouseClicked

    private void jButton10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseClicked
        DefaultListModel modelo = new DefaultListModel();
        modelo.removeAllElements();
        modelo.addElement(cbIngredientes_guiCrearProducto.getSelectedItem());
        listaIngredientes_guiCrearProducto.setModel(modelo);
        tempIngredientes.add((Ingredientes)cbIngredientes_guiCrearProducto.getSelectedItem());
    }//GEN-LAST:event_jButton10MouseClicked

    private void jButton11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseClicked
        Producto p = new Producto(tempIngredientes, Integer.parseInt(tfTiempoProducto.getText()), tfNombreProducto_guiCrearProducto.getText(), Double.parseDouble(tfPrecioProducto.getText()));
        menu.add(p);
        tfNombreProducto_guiCrearProducto.setText("");
        tfPrecioProducto.setText("");
        tfTiempoProducto.setText("");
        JOptionPane.showMessageDialog(null, "Producto agregado al menu");
        DefaultListModel modelo = (DefaultListModel)listaProductos_guiBodega.getModel();
        modelo.removeAllElements();
        for (int i = 0; i < menu.size(); i++) {
            modelo.addElement(menu.get(i));
        }
        listaProductos_guiBodega.setModel(modelo);
        tempIngredientes.clear();
    }//GEN-LAST:event_jButton11MouseClicked

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        String in = "";
        for (int i = 0; i < b.size(); i++) {
            in += b.getNombre(i) + "\n";
        }
        //in += b.getNombre(b.size());
        JOptionPane.showMessageDialog(null, in);
    }//GEN-LAST:event_jButton8MouseClicked

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
        guiComprarIngredientes.setModal(true);
        guiComprarIngredientes.pack();
        guiComprarIngredientes.setVisible(true);
    }//GEN-LAST:event_jButton9MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        DefaultListModel modelo = new DefaultListModel();
        modelo.removeAllElements();
        for (int i = 0; i < menu.size(); i++) {
            modelo.addElement(menu.get(i));
        }
        listaMenu_guiMenu.setModel(modelo);
        
        guiOrdenar.setModal(true);
        guiOrdenar.pack();
        guiOrdenar.setVisible(true);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        tempOrden.add((Producto)listaMenu_guiMenu.getSelectedValue());
        String total = jlTotal_guiMenu.getText();
        double tot = Double.parseDouble(total);
        tot = tot + ((Producto)listaMenu_guiMenu.getSelectedValue()).getPrecio();
        jlTotal_guiMenu.setText(Double.toString(tot));
        Orden o = new Orden(tempOrden);
        tempOrden.clear();
        colaOrdenes.add(o);
        JOptionPane.showMessageDialog(null, "Agregado");
        //jlTotal_guiMenu.setText("0.0");
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        
            if (lbCocinero1.getText().contentEquals("Inactivo")) {
                Orden o = colaOrdenes.element();
                ArrayList <Ingredientes> temp = new ArrayList<>();
                for (int i = 0; i < o.get(i).getListaIngredientes().size(); i++) {
                    temp.add(o.get(i).getListaIngredientes().get(i));
                }
                Cocinero c = new Cocinero(o, barra1, temp, lbCocinero1, b);
                c.start();
                for (int i = 0; i < camiones.size(); i++) {
                    if (camiones.get(i).getListaOrdenes().size() ==  20) {
                        Camion cc = new Camion();
                        cc.addOrden(o);
                        camiones.add(cc);
                    }else{
                        camiones.get(i).addOrden(o);
                    }
                }
            }else if (lbCocinero2.getText().contentEquals("Inactivo")) {
                Orden o = colaOrdenes.element();
                ArrayList <Ingredientes> temp = new ArrayList<>();
                for (int i = 0; i < o.get(i).getListaIngredientes().size(); i++) {
                    temp.add(o.get(i).getListaIngredientes().get(i));
                }
                Cocinero c = new Cocinero(o, barra2, temp, lbCocinero2, b);
                c.start();
                for (int i = 0; i < camiones.size(); i++) {
                    if (camiones.get(i).getListaOrdenes().size() ==  20) {
                        Camion cc = new Camion();
                        cc.addOrden(o);
                        camiones.add(cc);
                    }else{
                        camiones.get(i).addOrden(o);
                    }
                }
            }else if (lbCocinero3.getText().contentEquals("Inactivo")) {
                Orden o = colaOrdenes.element();
                ArrayList <Ingredientes> temp = new ArrayList<>();
                for (int i = 0; i < o.get(i).getListaIngredientes().size(); i++) {
                    temp.add(o.get(i).getListaIngredientes().get(i));
                }
                Cocinero c = new Cocinero(o, barra3, temp, lbCocinero3, b);
                c.start();
                for (int i = 0; i < camiones.size(); i++) {
                    if (camiones.get(i).getListaOrdenes().size() ==  20) {
                        Camion cc = new Camion();
                        cc.addOrden(o);
                        camiones.add(cc);
                    }else{
                        camiones.get(i).addOrden(o);
                    }
                }
            }else if (lbCocinero4.getText().contentEquals("Inactivo")) {
                Orden o = colaOrdenes.element();
                ArrayList <Ingredientes> temp = new ArrayList<>();
                for (int i = 0; i < o.get(i).getListaIngredientes().size(); i++) {
                    temp.add(o.get(i).getListaIngredientes().get(i));
                }
                Cocinero c = new Cocinero(o, barra4, temp, lbCocinero4, b);
                c.start();
                for (int i = 0; i < camiones.size(); i++) {
                    if (camiones.get(i).getListaOrdenes().size() ==  20) {
                        Camion cc = new Camion();
                        cc.addOrden(o);
                        camiones.add(cc);
                    }else{
                        camiones.get(i).addOrden(o);
                    }
                }
            }
            jlTotal_guiMenu.setText("0.0");
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        guiBodega.setModal(true);
        guiBodega.pack();
        guiBodega.setVisible(true);
        
        DefaultListModel modelo = new DefaultListModel();
        modelo.removeAllElements();
        for (int i = 0; i < menu.size(); i++) {
            modelo.addElement(menu.get(i));
        }
        listaProductos_guiBodega.setModel(modelo);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        guiCocina.setModal(true);
        guiCocina.pack();
        guiCocina.setVisible(true);
    }//GEN-LAST:event_jButton3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gui().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barra1;
    private javax.swing.JProgressBar barra10;
    private javax.swing.JProgressBar barra11;
    private javax.swing.JProgressBar barra12;
    private javax.swing.JProgressBar barra13;
    private javax.swing.JProgressBar barra14;
    private javax.swing.JProgressBar barra15;
    private javax.swing.JProgressBar barra16;
    private javax.swing.JProgressBar barra17;
    private javax.swing.JProgressBar barra18;
    private javax.swing.JProgressBar barra19;
    private javax.swing.JProgressBar barra2;
    private javax.swing.JProgressBar barra20;
    private javax.swing.JProgressBar barra3;
    private javax.swing.JProgressBar barra4;
    private javax.swing.JProgressBar barra5;
    private javax.swing.JProgressBar barra6;
    private javax.swing.JProgressBar barra7;
    private javax.swing.JProgressBar barra8;
    private javax.swing.JProgressBar barra9;
    private javax.swing.JComboBox cbIngredientes_guiCrearProducto;
    private javax.swing.JDialog guiBodega;
    private javax.swing.JDialog guiCocina;
    private javax.swing.JDialog guiComprarIngredientes;
    private javax.swing.JDialog guiCrearProducto;
    private javax.swing.JDialog guiEnviar;
    private javax.swing.JDialog guiOrdenar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel jlTotal_guiMenu;
    private javax.swing.JLabel lbCocinero1;
    private javax.swing.JLabel lbCocinero2;
    private javax.swing.JLabel lbCocinero3;
    private javax.swing.JLabel lbCocinero4;
    private javax.swing.JLabel lbCocinero5;
    private javax.swing.JList listaIngredientes_guiCrearProducto;
    private javax.swing.JList listaMenu_guiMenu;
    private javax.swing.JList listaProductos_guiBodega;
    private javax.swing.JTextField tfNombreIngrediente;
    private javax.swing.JTextField tfNombreProducto_guiCrearProducto;
    private javax.swing.JTextField tfPrecioProducto;
    private javax.swing.JTextField tfTiempoProducto;
    // End of variables declaration//GEN-END:variables
    Queue<Orden> colaOrdenes;
    Bodega b = new Bodega();
    ArrayList <Producto> menu = new ArrayList<>();
    ArrayList <Ingredientes> tempIngredientes = new ArrayList<>();
    ArrayList <Producto> tempOrden = new ArrayList<>();
    ArrayList <Camion> camiones = new ArrayList<>();
}
